### ISSUE TITLE
AppSearch how to use sort?

### ISSUE THREAD

**Issue by averatec1337** [elastic/enterprise-search-php#11]
I cannot figure out how to assing correct `SimpleObject` in `SearchRequestParams` to sort results by e.g. fieldA and then fieldB.
In previous package versions it wasn't type-hinted property so I could do something like this:
`$searchRequestParams->sort = [['fieldA' => 'desc'], ['fieldB' => 'desc']];`
But now it's type-hinted property so I can't do this.

Is it possible to provide OAS for enterprise search or OAS isn't flexible enough?

**Comment by ezimuel** [comment]
@kamil-karkus the `sort` parameter is now a `Elastic\EnterpriseSearch\AppSearch\Schema\SimpleObject` object (this is actually an empty class used only for namespace reason). This means you can pass the `fieldA` and `fieldB` as property of `SimpleObject` as follows:
```php
use Elastic\EnterpriseSearch\AppSearch\Schema\SimpleObject;

$sort = new SimpleObject();
$sort->fieldA = 'desc';
$sort->fieldB = 'desc';
$searchRequestParams->sort = $sort;
```

**Comment by averatec1337** [comment]
Already tried this and got 400 bad request, I'll provide more details later today

**Comment by ezimuel** [comment]
Ok, please paste the full PHP code including the endpoint usage, thanks.

**Comment by averatec1337** [comment]
@ezimuel I'm sorry for the delay.

Package version
```
elastic/enterprise-search            v7.14.0   Enterprise Search official PHP client
```
Code snippet
```php
        $appSearch = $this->client->appSearch();

        $searchRequestParams = new SearchRequestParams();
        $searchRequestParams->query = $query;
        $searchRequestParams->precision = 8;
        $searchRequestParams->sort = [[Enum::KEY_IN_STOCK => 'desc'], [Enum::KEY_NET_PRICE => 'desc']];
        $current = max(1, $page);
        $size = min($limit, 1000);

        $pagination = new \stdClass();
        $pagination->current = $current;
        $pagination->size = $size;
        $searchRequestParams->page = $pagination;
        $response = $appSearch
            ->search(new Search(Enum::ENGINE_NAME_PRODUCTS, $searchRequestParams))
            ->asArray();
```

Request body
```json
{"page":{"current":1,"size":100},"query":"long","sort":[{"in_stock":"desc"},{"net_price":"desc"}],"precision":8}
```

Response code 200 


------------------------------------------------------------------------
Package version
```
elastic/enterprise-search            v7.16.0   Enterprise Search official PHP client
```
Code snippet
```php
         $appSearch = $this->client->appSearch();

        $searchRequestParams = new SearchRequestParams($query);
        $searchRequestParams->precision = 8;
        $sort = new SimpleObject();
        $key1 = Enum::KEY_IN_STOCK;
        $sort->$key1 = 'desc';
        $key2 = Enum::KEY_NET_PRICE;
        $sort->$key2 = 'desc';
        $searchRequestParams->sort = $sort;
        $current = max(1, $page);
        $size = min($limit, 1000);

        $pagination = new PaginationResponseObject();
        $pagination->current = $current;
        $pagination->size = $size;
        $searchRequestParams->page = $pagination;
        $response = $appSearch
            ->search(new Search(Enum::ENGINE_NAME_PRODUCTS, $searchRequestParams))
            ->asArray();
```

Request body (sort isn't serialized correctly)
```json
{"query":"long","page":{"current":1,"size":100},"sort":{"in_stock":"desc","net_price":"desc"},"precision":8}
```

Response code 400

Response  body
```json
{"errors":["Sort contains an object with more than one key: in_stock and net_price"]}
```

**Comment by jdear** [comment]
> @kamil-karkus the `sort` parameter is now a `Elastic\EnterpriseSearch\AppSearch\Schema\SimpleObject` object (this is actually an empty class used only for namespace reason). This means you can pass the `fieldA` and `fieldB` as property of `SimpleObject` as follows:
> 
> ```
> use Elastic\EnterpriseSearch\AppSearch\Schema\SimpleObject;
> 
> $sort = new SimpleObject();
> $sort->fieldA = 'desc';
> $sort->fieldB = 'desc';
> $searchRequestParams->sort = $sort;
> ```

I'm seeing the same issue as @kamil-karkus. This code works when only sorting by one field, but I get a 400 Bad Request as soon as I add more than one field as @ezimuel did in this example.

**Comment by ezimuel** [comment]
I found the issue, the `sort` parameter can be an object or an `array` of objects. This feature is documented as [sorting on multiple fields](https://www.elastic.co/guide/en/app-search/7.17/sort.html#sort-multi-field-sorting). I will fix the issue with `7.17.0` release soon. I'm sorry for the inconvenience.

**Comment by averatec1337** [comment]
@ezimuel I don't want to rush you but is there any news?

**Comment by ezimuel** [comment]
Fixed in [v7.17.0](https://github.com/elastic/enterprise-search-php/releases/tag/v7.17.0), sorry for the delay :cold_sweat:

**Comment by myleshyson** [comment]
This is still broken for me. I'm using the dev-master branch and App Search 8.2 but still getting this error.

```json
{
  "errors": [
    "Sort contains an object with more than one key: title and title2"
  ]
}
```

here's a basic test  I did.
```php
        $params = new SearchRequestParams('hey');
        $params->sort = new SimpleObject();
        $params->sort->title = 'asc';
        $params->sort->title2 = 'asc';
        $response = $this->client->search(new Search('local-elements', $params));  
```

not sure if it makes sense for sort to be typed as a `SimpleObject` since the request can accept an array of objects. I think this can be fixed by just typing it as an array as well.

To be on the safe side all the `SimpleObject` types should probably just be typed as `SimpleObject|array`, if that property supports both structures.

**Comment by myleshyson** [comment]
ah you know what, looks like master is out of sync with the changes made to 7.17 to fix this. Any chance those can get merged in to the master branch?

**Comment by ezimuel** [comment]
@myleshyson we did not release the `enterprise-search-php` for App Search 8. We are working on it and release it soon. In the meantime, you can try using [7.17.0](https://github.com/elastic/enterprise-search-php/releases/tag/v7.17.0) release.

**Comment by jayjfletcher** [comment]
Has this been fully resolved anywhere? I'm still having this issues sorting on multiple columns with the latest version ... over a year later. No matter what I do i cant sort on multiple columns.
